# action.yml
name: 'Terraform Cloud Action'
description: 'Submit a run to Terraform Cloud.'
inputs:
  tfToken:
    description: 'Terraform Cloud Token.'
    required: true
  tfOrg:
    description: 'Terraform Cloud Organization.'
    required: true
  tfWorkspace:
    description: Terraform Cloud Workspace.'
  filePath:
    description: 'Archive (.tar.gz) to submit.'
  identifier:
    description: 'Unique identifier for workflow (e.g. Git SHA)'
  
outputs:
  runId: # id of output
    description: 'The Id of the run.'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'server'
  color: 'purple'